In [1]:
import requests
import json
from pprint import pprint
import os
import matplotlib.pyplot as plt
import pandas as pd
import csv

In [2]:
# open the raw dataset
csv_path = os.path.join("vaccination_raw.csv")
df_raw = pd.read_csv(csv_path, encoding='unicode_escape', header=[0,1,2])
df_raw

,Unnamed: 0_level_0,Influenza vaccination (General Population) - Age,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0,Unnamed: 5_level_0,Unnamed: 6_level_0,Unnamed: 7_level_0,Unnamed: 8_level_0,Unnamed: 9_level_0,...,Unnamed: 927_level_0,Unnamed: 928_level_0,Unnamed: 929_level_0,Unnamed: 930_level_0,Unnamed: 931_level_0,Unnamed: 932_level_0,Unnamed: 933_level_0,Unnamed: 934_level_0,Unnamed: 935_level_0,Unnamed: 936_level_0
,Unnamed: 0_level_1,³6 months,Unnamed: 2_level_1,Unnamed: 3_level_1,Unnamed: 4_level_1,Unnamed: 5_level_1,Unnamed: 6_level_1,Unnamed: 7_level_1,Unnamed: 8_level_1,Unnamed: 9_level_1,...,Unnamed: 927_level_1,Unnamed: 928_level_1,Unnamed: 929_level_1,Unnamed: 930_level_1,Unnamed: 931_level_1,Unnamed: 932_level_1,Unnamed: 933_level_1,Unnamed: 934_level_1,Unnamed: 935_level_1,Unnamed: 936_level_1
,Names,2010-11,LL,UL,CI,SAMPLE,TARGET,2011-12,LL,UL,...,UL,CI,SAMPLE,TARGET,2018-19,LL,UL,CI,SAMPLE,TARGET
0,Alabama,42.4,40.1,44.7,(±2.3),8221.0,70.0,41.6,39.7,43.5,...,50.7,(±7.8),445.0,70.0,36.5,29.6,43.4,(±6.9),460,70.0
1,Alaska,37.0,33.3,40.7,(±3.7),4082.0,70.0,34.7,32.2,37.2,...,50.4,(±7.7),858.0,70.0,41.6,35.3,47.9,(±6.3),930,70.0
2,Arizona,41.9,38.8,45.0,(±3.1),7714.0,70.0,38.2,35.8,40.6,...,54.9,(±8.9),1197.0,70.0,46.3,39.4,53.2,(±6.9),1013,70.0
3,Arkansas,44.2,40.9,47.5,(±3.3),5605.0,70.0,46.6,44.1,49.1,...,48.8,(±9.0),431.0,70.0,36.1,28.3,43.9,(±7.8),365,70.0
4,California,38.9,37.6,40.2,(±1.3),17752.0,70.0,40.5,36.2,44.8,...,46.8,(±3.6),1582.0,70.0,45.0,40.6,49.4,(±4.4),1332,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,Region 7,45.9,44.6,47.2,(±1.3),44668.0,70.0,45.7,44.7,46.7,...,44.8,(±4.6),1769.0,70.0,50.3,45.7,54.9,(±4.6),1778,70.0
59,Region 8,45.3,44.0,46.6,(±1.3),50272.0,70.0,42.9,41.9,43.9,...,48.5,(±4.1),3732.0,70.0,50.2,46.3,54.1,(±3.9),3717,70.0
60,Region 9,39.6,38.5,40.7,(±1.1),37303.0,70.0,38.7,37.2,40.2,...,46.2,(±2.9),7394.0,70.0,45.7,42.2,49.2,(±3.5),7331,70.0
61,Region 10,40.0,38.7,41.3,(±1.3),35002.0,70.0,39.4,38.3,40.5,...,48.9,(±4.1),2664.0,70.0,52.6,48.9,56.3,(±3.7),2826,70.0
62,HP 2020 Target,70.0,NaN,NaN,NaN,NaN,NaN,70.0,NaN,NaN,...,NaN,NaN,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN

In [3]:
# make a copy of raw dataset to tailor
df_clean = df_raw.copy()
df_clean

,Unnamed: 0_level_0,Influenza vaccination (General Population) - Age,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0,Unnamed: 5_level_0,Unnamed: 6_level_0,Unnamed: 7_level_0,Unnamed: 8_level_0,Unnamed: 9_level_0,...,Unnamed: 927_level_0,Unnamed: 928_level_0,Unnamed: 929_level_0,Unnamed: 930_level_0,Unnamed: 931_level_0,Unnamed: 932_level_0,Unnamed: 933_level_0,Unnamed: 934_level_0,Unnamed: 935_level_0,Unnamed: 936_level_0
,Unnamed: 0_level_1,³6 months,Unnamed: 2_level_1,Unnamed: 3_level_1,Unnamed: 4_level_1,Unnamed: 5_level_1,Unnamed: 6_level_1,Unnamed: 7_level_1,Unnamed: 8_level_1,Unnamed: 9_level_1,...,Unnamed: 927_level_1,Unnamed: 928_level_1,Unnamed: 929_level_1,Unnamed: 930_level_1,Unnamed: 931_level_1,Unnamed: 932_level_1,Unnamed: 933_level_1,Unnamed: 934_level_1,Unnamed: 935_level_1,Unnamed: 936_level_1
,Names,2010-11,LL,UL,CI,SAMPLE,TARGET,2011-12,LL,UL,...,UL,CI,SAMPLE,TARGET,2018-19,LL,UL,CI,SAMPLE,TARGET
0,Alabama,42.4,40.1,44.7,(±2.3),8221.0,70.0,41.6,39.7,43.5,...,50.7,(±7.8),445.0,70.0,36.5,29.6,43.4,(±6.9),460,70.0
1,Alaska,37.0,33.3,40.7,(±3.7),4082.0,70.0,34.7,32.2,37.2,...,50.4,(±7.7),858.0,70.0,41.6,35.3,47.9,(±6.3),930,70.0
2,Arizona,41.9,38.8,45.0,(±3.1),7714.0,70.0,38.2,35.8,40.6,...,54.9,(±8.9),1197.0,70.0,46.3,39.4,53.2,(±6.9),1013,70.0
3,Arkansas,44.2,40.9,47.5,(±3.3),5605.0,70.0,46.6,44.1,49.1,...,48.8,(±9.0),431.0,70.0,36.1,28.3,43.9,(±7.8),365,70.0
4,California,38.9,37.6,40.2,(±1.3),17752.0,70.0,40.5,36.2,44.8,...,46.8,(±3.6),1582.0,70.0,45.0,40.6,49.4,(±4.4),1332,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,Region 7,45.9,44.6,47.2,(±1.3),44668.0,70.0,45.7,44.7,46.7,...,44.8,(±4.6),1769.0,70.0,50.3,45.7,54.9,(±4.6),1778,70.0
59,Region 8,45.3,44.0,46.6,(±1.3),50272.0,70.0,42.9,41.9,43.9,...,48.5,(±4.1),3732.0,70.0,50.2,46.3,54.1,(±3.9),3717,70.0
60,Region 9,39.6,38.5,40.7,(±1.1),37303.0,70.0,38.7,37.2,40.2,...,46.2,(±2.9),7394.0,70.0,45.7,42.2,49.2,(±3.5),7331,70.0
61,Region 10,40.0,38.7,41.3,(±1.3),35002.0,70.0,39.4,38.3,40.5,...,48.9,(±4.1),2664.0,70.0,52.6,48.9,56.3,(±3.7),2826,70.0
62,HP 2020 Target,70.0,NaN,NaN,NaN,NaN,NaN,70.0,NaN,NaN,...,NaN,NaN,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN

In [4]:
# clean the header
df_clean.columns = df_clean.columns.droplevel([0,1])
df_clean

,Names,2010-11,LL,UL,CI,SAMPLE,TARGET,2011-12,LL,UL,...,UL,CI,SAMPLE,TARGET,2018-19,LL,UL,CI,SAMPLE,TARGET
0,Alabama,42.4,40.1,44.7,(±2.3),8221.0,70.0,41.6,39.7,43.5,...,50.7,(±7.8),445.0,70.0,36.5,29.6,43.4,(±6.9),460,70.0
1,Alaska,37.0,33.3,40.7,(±3.7),4082.0,70.0,34.7,32.2,37.2,...,50.4,(±7.7),858.0,70.0,41.6,35.3,47.9,(±6.3),930,70.0
2,Arizona,41.9,38.8,45.0,(±3.1),7714.0,70.0,38.2,35.8,40.6,...,54.9,(±8.9),1197.0,70.0,46.3,39.4,53.2,(±6.9),1013,70.0
3,Arkansas,44.2,40.9,47.5,(±3.3),5605.0,70.0,46.6,44.1,49.1,...,48.8,(±9.0),431.0,70.0,36.1,28.3,43.9,(±7.8),365,70.0
4,California,38.9,37.6,40.2,(±1.3),17752.0,70.0,40.5,36.2,44.8,...,46.8,(±3.6),1582.0,70.0,45.0,40.6,49.4,(±4.4),1332,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,Region 7,45.9,44.6,47.2,(±1.3),44668.0,70.0,45.7,44.7,46.7,...,44.8,(±4.6),1769.0,70.0,50.3,45.7,54.9,(±4.6),1778,70.0
59,Region 8,45.3,44.0,46.6,(±1.3),50272.0,70.0,42.9,41.9,43.9,...,48.5,(±4.1),3732.0,70.0,50.2,46.3,54.1,(±3.9),3717,70.0
60,Region 9,39.6,38.5,40.7,(±1.1),37303.0,70.0,38.7,37.2,40.2,...,46.2,(±2.9),7394.0,70.0,45.7,42.2,49.2,(±3.5),7331,70.0
61,Region 10,40.0,38.7,41.3,(±1.3),35002.0,70.0,39.4,38.3,40.5,...,48.9,(±4.1),2664.0,70.0,52.6,48.9,56.3,(±3.7),2826,70.0
62,HP 2020 Target,70.0,NaN,NaN,NaN,NaN,NaN,70.0,NaN,NaN,...,NaN,NaN,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN

In [5]:
# set index by "Names"
df_clean = df_clean.set_index('Names')

In [6]:
# delete irrelevant columns
df_clean.drop(["LL","UL","CI","SAMPLE","TARGET"],axis=1, inplace=True)
df_clean

,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,2016-17,2017-18,2018-19,2010-11,...,2018-19,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,2016-17,2017-18,2018-19
Names,,,,,,,,,,,,,,,,,,,,,
Alabama,42.4,41.6,45.7,48.3,45.8,43.9,43.9,42.4,48.3,45.9,...,64.2,39.2,45.2,44.0,46.6,42.9,45.8,38.9,42.9,36.5
Alaska,37.0,34.7,39.7,41.7,44.0,37.9,39.1,40.2,44.1,46.8,...,33.0,40.7,37.7,39.2,47.0,44.7,37.2,44.2,42.7,41.6
Arizona,41.9,38.2,38.3,38.5,41.6,41.5,41.8,38.9,45.6,49.0,...,41.9,47.2,48.2,39.4,42.0,43.4,46.9,39.6,46.0,46.3
Arkansas,44.2,46.6,47.0,49.7,50.5,45.4,46.2,41.7,48.8,56.1,...,50.7,47.3,53.2,36.6,41.5,54.3,39.6,50.2,39.8,36.1
California,38.9,40.5,44.2,NR,44.2,43.7,48.0,40.0,47.4,50.7,...,44.6,37.0,34.6,48.3,NR,48.7,43.0,51.7,43.2,45.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Region 7,45.9,45.7,46.8,48.5,50.6,48.0,48.0,43.9,51.7,48.6,...,51.5,50.8,43.8,50.2,46.4,50.2,46.3,47.2,40.2,50.3
Region 8,45.3,42.9,47.0,47.7,48.6,47.1,47.1,43.0,49.5,53.5,...,46.2,44.3,43.5,49.0,51.7,53.0,48.3,53.9,44.4,50.2
Region 9,39.6,38.7,43.5,46.5,43.8,43.2,46.4,39.9,46.7,50.8,...,43.9,39.4,38.3,47.7,51.8,48.5,44.3,50.3,43.3,45.7
Region 10,40.0,39.4,43.8,44.9,46.7,44.5,44.2,44.1,50.2,45.5,...,49.6,36.2,38.5,45.6,45.1,46.3,45.2,45.3,44.8,52.6
HP 2020 Target,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,...,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0

In [7]:
# pick up data for year 2014-15
df_2014 = df_clean[["2014-15"]]
df_2014

,2014-15,2014-15,2014-15,2014-15,2014-15,2014-15,2014-15,2014-15,2014-15,2014-15,2014-15,2014-15,2014-15,2014-15,2014-15,2014-15,2014-15,2014-15
Names,,,,,,,,,,,,,,,,,,
Alabama,45.8,57.0,63.6,61.2,46.2,42.6,36.8,46.8,33.2,31.3,39.0,29.4,47.6,65.3,47.2,41.5,55.9,42.9
Alaska,44.0,53.6,65.2,59.3,33.6,40.9,38.3,42.6,36.9,37.5,33.5,37.6,40.2,57.5,43.5,54.2,40.2,44.7
Arizona,41.6,52.0,66.2,52.9,40.6,38.4,31.9,41.4,29.2,27.5,35.2,25.8,41.9,62.4,42.7,30.5,40.4,43.4
Arkansas,50.5,66.0,67.1,71.9,57.3,45.8,39.1,40.9,38.8,37.0,37.3,37.3,43.4,69.6,50.5,43.0,68.4,54.3
California,44.2,59.2,72.0,63.4,44.1,39.7,34.4,51.1,30.1,29.7,42.1,27.8,44.9,64.7,46.6,39.8,40.7,48.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Region 7,50.6,56.4,69.7,58.5,43.3,48.9,42.7,53.4,39.5,37.8,44.2,36.5,51.8,72.7,51.0,46.7,50.7,50.2
Region 8,48.6,57.1,70.9,57.2,46.3,45.9,41.0,50.6,39.0,37.9,45.0,37.1,47.7,68.6,48.6,50.8,46.2,53.0
Region 9,43.8,58.2,71.0,61.8,43.9,39.5,34.0,49.1,30.1,29.3,40.4,27.5,44.6,64.3,45.6,38.4,40.7,48.5
Region 10,46.7,56.2,68.5,58.2,42.6,44.0,39.0,45.8,37.1,35.9,39.9,35.0,45.5,64.8,46.3,48.0,50.1,46.3
HP 2020 Target,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0

In [8]:
# define each columns 
df_2014.columns = ['< 6 months', '6 months - 17 years', '6 months - 4 years', '5-12 years', 
                   '13-17 years', '³18 years','18-64 years','18-64 years at high risk',
                   '18-64 years not at high risk','18-49 years','18-49 years at high risk',
                   '18-49 years not at high risk','50-64 years','> 65 years','White',
                   'Black','Hispanic','Other Races']
df_2014

,< 6 months,6 months - 17 years,6 months - 4 years,5-12 years,13-17 years,³18 years,18-64 years,18-64 years at high risk,18-64 years not at high risk,18-49 years,18-49 years at high risk,18-49 years not at high risk,50-64 years,> 65 years,White,Black,Hispanic,Other Races
Names,,,,,,,,,,,,,,,,,,
Alabama,45.8,57.0,63.6,61.2,46.2,42.6,36.8,46.8,33.2,31.3,39.0,29.4,47.6,65.3,47.2,41.5,55.9,42.9
Alaska,44.0,53.6,65.2,59.3,33.6,40.9,38.3,42.6,36.9,37.5,33.5,37.6,40.2,57.5,43.5,54.2,40.2,44.7
Arizona,41.6,52.0,66.2,52.9,40.6,38.4,31.9,41.4,29.2,27.5,35.2,25.8,41.9,62.4,42.7,30.5,40.4,43.4
Arkansas,50.5,66.0,67.1,71.9,57.3,45.8,39.1,40.9,38.8,37.0,37.3,37.3,43.4,69.6,50.5,43.0,68.4,54.3
California,44.2,59.2,72.0,63.4,44.1,39.7,34.4,51.1,30.1,29.7,42.1,27.8,44.9,64.7,46.6,39.8,40.7,48.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Region 7,50.6,56.4,69.7,58.5,43.3,48.9,42.7,53.4,39.5,37.8,44.2,36.5,51.8,72.7,51.0,46.7,50.7,50.2
Region 8,48.6,57.1,70.9,57.2,46.3,45.9,41.0,50.6,39.0,37.9,45.0,37.1,47.7,68.6,48.6,50.8,46.2,53.0
Region 9,43.8,58.2,71.0,61.8,43.9,39.5,34.0,49.1,30.1,29.3,40.4,27.5,44.6,64.3,45.6,38.4,40.7,48.5
Region 10,46.7,56.2,68.5,58.2,42.6,44.0,39.0,45.8,37.1,35.9,39.9,35.0,45.5,64.8,46.3,48.0,50.1,46.3
HP 2020 Target,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0

In [9]:
# delete the overlapped bins 
df_2014_clean = df_2014[['< 6 months','6 months - 4 years','5-12 years','13-17 years',
                        '18-49 years','50-64 years','> 65 years','White','Black','Hispanic','Other Races']]
df_2014_clean = df_2014_clean.reset_index()
df_2014_clean

,Names,< 6 months,6 months - 4 years,5-12 years,13-17 years,18-49 years,50-64 years,> 65 years,White,Black,Hispanic,Other Races
0,Alabama,45.8,63.6,61.2,46.2,31.3,47.6,65.3,47.2,41.5,55.9,42.9
1,Alaska,44.0,65.2,59.3,33.6,37.5,40.2,57.5,43.5,54.2,40.2,44.7
2,Arizona,41.6,66.2,52.9,40.6,27.5,41.9,62.4,42.7,30.5,40.4,43.4
3,Arkansas,50.5,67.1,71.9,57.3,37.0,43.4,69.6,50.5,43.0,68.4,54.3
4,California,44.2,72.0,63.4,44.1,29.7,44.9,64.7,46.6,39.8,40.7,48.7
...,...,...,...,...,...,...,...,...,...,...,...,...
58,Region 7,50.6,69.7,58.5,43.3,37.8,51.8,72.7,51.0,46.7,50.7,50.2
59,Region 8,48.6,70.9,57.2,46.3,37.9,47.7,68.6,48.6,50.8,46.2,53.0
60,Region 9,43.8,71.0,61.8,43.9,29.3,44.6,64.3,45.6,38.4,40.7,48.5
61,Region 10,46.7,68.5,58.2,42.6,35.9,45.5,64.8,46.3,48.0,50.1,46.3
62,HP 2020 Target,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0

In [10]:
# repeat the steps above to get dataframe for year 2015-16,2016-17,2017-18,2018-19
df_2015 = df_clean[["2015-16"]]
df_2015.columns = ['< 6 months', '6 months - 17 years', '6 months - 4 years', '5-12 years', 
                   '13-17 years', '³18 years','18-64 years','18-64 years at high risk',
                   '18-64 years not at high risk','18-49 years','18-49 years at high risk',
                   '18-49 years not at high risk','50-64 years','> 65 years','White',
                   'Black','Hispanic','Other Races']
df_2015_clean = df_2015[['< 6 months','6 months - 4 years','5-12 years','13-17 years',
                        '18-49 years','50-64 years','> 65 years','White','Black','Hispanic','Other Races']]
df_2015_clean = df_2015_clean.reset_index()
df_2015_clean

,Names,< 6 months,6 months - 4 years,5-12 years,13-17 years,18-49 years,50-64 years,> 65 years,White,Black,Hispanic,Other Races
0,Alabama,43.9,70.2,64.8,50.0,29.1,40.8,61.1,43.4,42.6,61.1,45.8
1,Alaska,37.9,56.7,49.4,39.7,28.8,39.0,51.5,38.1,51.6,35.5,37.2
2,Arizona,41.5,58.0,57.2,40.1,29.0,39.0,59.4,41.7,46.2,39.0,46.9
3,Arkansas,45.4,74.3,70.1,54.5,28.5,43.9,59.1,45.1,45.9,55.5,39.6
4,California,43.7,70.0,63.5,47.4,32.5,38.3,61.1,47.8,40.7,41.1,43.0
...,...,...,...,...,...,...,...,...,...,...,...,...
58,Region 7,48.0,70.5,63.6,42.9,34.1,47.2,68.6,48.3,52.0,45.5,46.3
59,Region 8,47.1,70.3,59.8,45.6,35.2,47.9,65.6,47.2,53.2,46.7,48.3
60,Region 9,43.2,68.2,62.5,46.0,31.7,38.4,60.9,45.5,40.3,40.9,44.3
61,Region 10,44.5,69.3,57.1,44.1,32.1,43.9,62.0,44.9,41.6,43.6,45.2
62,HP 2020 Target,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0

In [11]:
df_2016 = df_clean[["2016-17"]]
df_2016.columns = ['< 6 months', '6 months - 17 years', '6 months - 4 years', '5-12 years', 
                   '13-17 years', '³18 years','18-64 years','18-64 years at high risk',
                   '18-64 years not at high risk','18-49 years','18-49 years at high risk',
                   '18-49 years not at high risk','50-64 years','> 65 years','White',
                   'Black','Hispanic','Other Races']
df_2016_clean = df_2016[['< 6 months','6 months - 4 years','5-12 years','13-17 years',
                        '18-49 years','50-64 years','> 65 years','White','Black','Hispanic','Other Races']]
df_2016_clean = df_2016_clean.reset_index()
df_2016_clean

,Names,< 6 months,6 months - 4 years,5-12 years,13-17 years,18-49 years,50-64 years,> 65 years,White,Black,Hispanic,Other Races
0,Alabama,43.9,68.4,55.1,43.2,28.5,47.5,63.0,45.2,39.2,55.4,38.9
1,Alaska,39.1,43.9,52.2,38.2,31.6,38.0,55.6,37.8,48.8,36.0,44.2
2,Arizona,41.8,60.4,54.6,38.0,28.1,42.5,60.8,43.3,33.6,41.1,39.6
3,Arkansas,46.2,63.7,66.0,49.0,30.1,46.9,62.8,44.9,47.5,53.1,50.2
4,California,48.0,73.3,61.5,53.9,36.4,45.7,66.2,50.4,37.0,46.6,51.7
...,...,...,...,...,...,...,...,...,...,...,...,...
58,Region 7,48.0,69.3,58.3,44.0,36.0,46.1,68.0,48.0,44.8,51.7,47.2
59,Region 8,47.1,69.7,59.5,42.8,35.3,47.1,66.2,46.2,50.8,48.0,53.9
60,Region 9,46.4,70.4,59.7,50.3,34.4,45.0,64.4,47.9,36.7,44.9,50.3
61,Region 10,44.2,64.1,54.8,42.6,32.3,44.0,62.4,44.0,46.9,45.3,45.3
62,HP 2020 Target,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0

In [12]:
df_2017 = df_clean[["2017-18"]]
df_2017.columns = ['< 6 months', '6 months - 17 years', '6 months - 4 years', '5-12 years', 
                   '13-17 years', '³18 years','18-64 years','18-64 years at high risk',
                   '18-64 years not at high risk','18-49 years','18-49 years at high risk',
                   '18-49 years not at high risk','50-64 years','> 65 years','White',
                   'Black','Hispanic','Other Races']
df_2017_clean = df_2017[['< 6 months','6 months - 4 years','5-12 years','13-17 years',
                        '18-49 years','50-64 years','> 65 years','White','Black','Hispanic','Other Races']]
df_2017_clean = df_2017_clean.reset_index()
df_2017_clean

,Names,< 6 months,6 months - 4 years,5-12 years,13-17 years,18-49 years,50-64 years,> 65 years,White,Black,Hispanic,Other Races
0,Alabama,42.4,61.7,56.0,42.9,27.0,41.0,65.4,42.7,39.5,51.4,42.9
1,Alaska,40.2,60.4,45.3,43.0,35.3,33.7,51.9,39.9,47.2,33.9,42.7
2,Arizona,38.9,67.8,51.8,37.3,26.6,34.9,56.2,39.5,37.7,36.1,46.0
3,Arkansas,41.7,62.9,66.2,59.9,24.8,38.5,54.7,41.5,38.8,56.0,39.8
4,California,40.0,67.8,58.3,48.7,25.3,39.3,58.1,44.4,35.0,35.2,43.2
...,...,...,...,...,...,...,...,...,...,...,...,...
58,Region 7,43.9,63.7,56.7,44.2,30.8,40.5,64.0,43.9,44.7,46.0,40.2
59,Region 8,43.0,68.2,57.7,43.3,30.7,41.2,60.6,42.8,42.3,43.8,44.4
60,Region 9,39.9,66.9,56.9,47.2,25.5,38.5,58.4,43.3,35.4,35.2,43.3
61,Region 10,44.1,67.2,56.7,48.5,31.0,43.6,61.1,44.9,47.4,39.8,44.8
62,HP 2020 Target,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0

In [78]:
df_2018 = df_clean[["2018-19"]]
df_2018.columns = ['< 6 months', '6 months - 17 years', '6 months - 4 years', '5-12 years', 
                   '13-17 years', '³18 years','18-64 years','18-64 years at high risk',
                   '18-64 years not at high risk','18-49 years','18-49 years at high risk',
                   '18-49 years not at high risk','50-64 years','> 65 years','White',
                   'Black','Hispanic','Other Races']
df_2018_clean = df_2018[['< 6 months','6 months - 4 years','5-12 years','13-17 years',
                        '18-49 years','50-64 years','> 65 years','White','Black','Hispanic','Other Races']]
df_2018_clean = df_2018_clean.reset_index()
df_2018_clean

,Names,< 6 months,6 months - 4 years,5-12 years,13-17 years,18-49 years,50-64 years,> 65 years,White,Black,Hispanic,Other Races
0,Alabama,48.3,68.7,64.0,48.2,30.7,51.5,71.5,50.1,43.4,64.2,36.5
1,Alaska,44.1,63.8,56.2,44.7,34.8,40.4,61.2,45.4,48.2,33.0,41.6
2,Arizona,45.6,63.3,58.6,46.8,31.6,45.5,64.4,47.1,48.6,41.9,46.3
3,Arkansas,48.8,69.2,64.5,57.0,34.4,47.7,62.8,49.5,46.6,50.7,36.1
4,California,47.4,77.1,66.6,49.9,33.7,43.8,69.0,52.3,40.8,44.6,45.0
...,...,...,...,...,...,...,...,...,...,...,...,...
58,Region 7,51.7,72.6,62.7,51.5,38.6,49.9,71.5,52.5,44.8,51.5,50.3
59,Region 8,49.5,70.3,62.0,50.1,36.9,49.8,68.0,49.6,58.9,46.2,50.2
60,Region 9,46.7,74.4,64.4,48.9,32.7,43.6,68.0,50.5,40.0,43.9,45.7
61,Region 10,50.2,74.3,61.7,48.0,37.1,49.5,69.4,50.3,47.1,49.6,52.6
62,HP 2020 Target,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0,70.0

In [58]:
# output each dataset
df_2014_clean.to_csv("vaccination_2014-15.csv", index=False, header=True)
df_2015_clean.to_csv("vaccination_2015-16.csv", index=False, header=True)
df_2016_clean.to_csv("vaccination_2016-17.csv", index=False, header=True)
df_2017_clean.to_csv("vaccination_2017-18.csv", index=False, header=True)
df_2018_clean.to_csv("vaccination_2018-19.csv", index=False, header=True)